type User{
    id: ID!
    name: String!
    email: String!
    company: Company!
}
type Company{
    id: ID!
    name: String!
    address: String!
}

type Query {
    getUser: User!
    getUsers: [User!]!
}
